"""empty message

Revision ID: 7f9318643606
Revises: e615e14a4abf
Create Date: 2021-11-26 21:53:55.650309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9318643606'
down_revision = 'e615e14a4abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('title_page_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog', 'image', ['title_page_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'title_page_id')
    # ### end Alembic commands ###
