"""empty message

Revision ID: 8d051344e50e
Revises: 7f9318643606
Create Date: 2021-11-27 15:33:54.619948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d051344e50e'
down_revision = '7f9318643606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'name')
    # ### end Alembic commands ###
