"""empty message

Revision ID: e58d31b1aa6c
Revises: 577639460727
Create Date: 2021-11-20 21:03:14.568671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58d31b1aa6c'
down_revision = '577639460727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
